### PR TITLE
Support multi line test cases

### PR DESCRIPTION
**Pull request by tysng**
Right now, the test script only looks at the last line of the test file and compare the output with this line. This PR makes the test script support multiple lines of comments (i.e. expected output).

### CODE REVIEW

**Comment by moziliar** [comment]
Will it take all the comments as the test output for comparison? Or will it limit the number of lines to only the bottom ones, allowing the developer to write comments elsewhere?

**Comment by tysng** [comment]
Yep, it will only look at the bottom comments. All of the existing test cases worked as per normal.

**Comment by moziliar** [comment]
@tysng Awesome. Looks good to me, so long as it does not introduce new things? Line parsing seems fine.

**Comment by tysng** [comment]
See https://github.com/source-academy/source-programs/pull/36

**Pull request closed without merging**
